=== api-evangelist/propertyware/json-schema/adjustment.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Adjustment",
  "description": "Adjustment",
  "type": "object",
  "required": [
    "amount",
    "date"
  ],
  "properties": {
    "amount": {
      "type": "number",
      "format": "double",
      "description": "Amount."
    },
    "comments": {
      "type": "string",
      "description": "Comments."
    },
    "createdBy": {
      "type": "string",
      "description": "User who created the record."
    },
    "createdDateTime": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time the record was created. (Timezone: UTC)"
    },
    "date": {
      "type": "string",
      "format": "date",
      "description": "Post date."
    },
    "glAccountID": {
      "type": "integer",
      "format": "int64",
      "description": "Id of the general ledger account associated with this charge."
    },
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "Unique identifier."
    },
    "lastModifiedBy": {
      "type": "string",
      "description": "User who last modified the record."
    },
    "lastModifiedDateTime": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time the record was last modified. (Timezone: UTC)"
    },
    "leaseID": {
      "type": "integer",
      "format": "int64",
      "description": "Id of the lease associated with this charge."
    },
    "portfolioID": {
      "type": "integer",
      "format": "int64",
      "description": "Id of the portfolio associated with this charge."
    },
    "refNo": {
      "type": "string",
      "description": "Reference number."
    }
  }
}

=== api-evangelist/propertyware/examples/adjustment.json
{
  "amount": 1.0,
  "comments": "example_comments",
  "createdBy": "example_createdBy",
  "createdDateTime": "2024-01-01T00:00:00Z",
  "date": "2024-01-01",
  "glAccountID": 1,
  "id": 1,
  "lastModifiedBy": "example_lastModifiedBy",
  "lastModifiedDateTime": "2024-01-01T00:00:00Z",
  "leaseID": 1,
  "portfolioID": 1,
  "refNo": "example_refNo"
}
