=== api-evangelist/propertyware/json-schema/bank-deposit.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "BankDeposit",
  "description": "Bank Deposit",
  "type": "object",
  "properties": {
    "createdBy": {
      "type": "string",
      "description": "User who created the record."
    },
    "createdDateTime": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time the record was created. (Timezone: UTC)"
    },
    "dateOpened": {
      "type": "string",
      "description": "Date opened."
    },
    "description": {
      "type": "string",
      "description": "Description."
    },
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "Unique identifier."
    },
    "lastModifiedBy": {
      "type": "string",
      "description": "User who last modified the record."
    },
    "lastModifiedDateTime": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time the record was last modified. (Timezone: UTC)"
    },
    "name": {
      "type": "string",
      "description": "Bank deposit name."
    },
    "status": {
      "type": "string",
      "description": "Status."
    }
  }
}

=== api-evangelist/propertyware/examples/bank-deposit.json
{
  "createdBy": "example_createdBy",
  "createdDateTime": "2024-01-01T00:00:00Z",
  "dateOpened": "example_dateOpened",
  "description": "example_description",
  "id": 1,
  "lastModifiedBy": "example_lastModifiedBy",
  "lastModifiedDateTime": "2024-01-01T00:00:00Z",
  "name": "example_name",
  "status": "example_status"
}
