=== api-evangelist/propertyware/json-schema/g-l-item.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GLItem",
  "description": "General Ledger Transaction",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string",
      "description": "Comments."
    },
    "createdBy": {
      "type": "string",
      "description": "User who created the record."
    },
    "createdDateTime": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time the record was created. (Timezone: UTC)"
    },
    "glentries": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Entry"
      }
    },
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "Unique identifier."
    },
    "lastModifiedBy": {
      "type": "string",
      "description": "User who last modified the record."
    },
    "lastModifiedDateTime": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time the record was last modified. (Timezone: UTC)"
    },
    "leaseID": {
      "type": "integer",
      "format": "int64",
      "description": "Id of the lease associated with this transaction."
    },
    "ownerID": {
      "type": "integer",
      "format": "int64",
      "description": "Id of the owner associated with this transaction."
    },
    "transactionType": {
      "type": "string",
      "description": "Transaction type."
    },
    "txDate": {
      "type": "string",
      "format": "date",
      "description": "Transaction date."
    },
    "vendorID": {
      "type": "integer",
      "format": "int64",
      "description": "Id of the vendor associated with this transaction."
    }
  }
}

=== api-evangelist/propertyware/examples/g-l-item.json
{
  "comment": "example_comment",
  "createdBy": "example_createdBy",
  "createdDateTime": "2024-01-01T00:00:00Z",
  "glentries": [],
  "id": 1,
  "lastModifiedBy": "example_lastModifiedBy",
  "lastModifiedDateTime": "2024-01-01T00:00:00Z",
  "leaseID": 1,
  "ownerID": 1,
  "transactionType": "example_transactionType",
  "txDate": "2024-01-01",
  "vendorID": 1
}
