=== api-evangelist/propertyware/json-schema/save-owner.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "SaveOwner",
  "description": "Save Owner Contact",
  "type": "object",
  "required": [
    "firstName",
    "lastName"
  ],
  "properties": {
    "address": {
      "$ref": "#/components/schemas/SaveAddress"
    },
    "email": {
      "type": "string",
      "description": "Owner EMail."
    },
    "firstName": {
      "type": "string",
      "description": "Owner First Name."
    },
    "homePhone": {
      "type": "string",
      "description": "Owner Home Phone."
    },
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "Unique identifier."
    },
    "lastName": {
      "type": "string",
      "description": "Owner Last Name."
    },
    "mobilePhone": {
      "type": "string",
      "description": "Owner Mobile Phone."
    },
    "otherPhone": {
      "type": "string",
      "description": "Owner Other Phone."
    },
    "percentageOwnership": {
      "type": "number",
      "format": "double",
      "description": "Ownership percentage."
    },
    "workPhone": {
      "type": "string",
      "description": "Owner Work Phone."
    }
  }
}

=== api-evangelist/propertyware/examples/save-owner.json
{
  "address": "example_address",
  "email": "example_email",
  "firstName": "example_firstName",
  "homePhone": "example_homePhone",
  "id": 1,
  "lastName": "example_lastName",
  "mobilePhone": "example_mobilePhone",
  "otherPhone": "example_otherPhone",
  "percentageOwnership": 1.0,
  "workPhone": "example_workPhone"
}
